### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Iniciando** [Smokexyz/HerculesBG#1]
I started testing the script now and found some errors. Are they:
 
* When the player joins the battlefield, if he is stopped / seated at the time of registration and the game starts, he is expelled from the battle. That is, the inactive time (AFK) is being counted off the BG map.
 
* When thrown out of the battlefield due to not moving (AFK), sometimes the kicked player gets stuck at his return point, and still remains in the guild, as if he were inside the BG map. 

Spoiler Show
https://postimg.org/image/tnozymb0d
 
 
* You are not allowed to use guild skill within battle, they do not appear. Guild Level is 1, and should be 50.

Spoiler Show
https://postimg.org/image/b9egumypp
https://postimg.org/image/nlhd84mkd
 
@edit
* When the admin / Game Master uses @reloadscript and has a battle in progress, the battle in question ends, without expelling the players from within the map, and begins to announce the new battle.
 
* When using "Team Building Mode" as 2 - Balanced, the game hangs at the time the game starts, without players, because it does not teleport the players to the battle map.
// Team Building Mode: 0 = Linear, 1 = Random, 2 = Balanced
Set .TeamBuildingMode, 1;
 
* By clicking on the kafra in the bat_room room, nothing happens.

OBS: I will continue the tests and if I find new errors, I will report.I started testing the script now and found some errors. Are they:

Posted in topic: http://herc.ws/board/topic/14083-hercules-battlegrounds/#entry79726

**Comment by Smokexyz** [comment]
@Iniciando For the guild information, it's the same as it was in eAmod, the guild cannot level up and guild skills cannot be used. 
Also when using @reloadscript, the bgs are runned in scripts, therefore they stop. So the only proper thing to do would be asking them to relogin and keeping the map unsaveable.

**Comment by Iniciando** [comment]
Sorry, but in official eAmod it is possible, yes, use guild skills. This is the reason guild was created, only to be used guild skills. The BG system itself already creates teams, it would not be necessary to create a guild for this. Follows images of the official BG - eAmod system used in Brazil.
https://postimg.org/gallery/1cljap3mo/578aea56/

Any questions, please ask me

**Comment by Smokexyz** [comment]
@Iniciando Guild skills should be working now. 
Option 2 for team building mode is not yet available.

**Comment by Iniciando** [comment]
Errors and warning to compile.

http://herc.ws/board/topic/14083-hercules-battlegrounds/?p=79865

As for kafra, it is in the file \ npc \ custom \ hBG \ bg_common. But I may be able to solve it.

**Comment by Smokexyz** [comment]
@Iniciando Cannot reproduce, please pull a fresh copy and re-try compiling. If any occurs, please open a new issue.

**Comment by Iniciando** [comment]
@Smokexyz Why was the problem closed? You said you did not solve it completely.

commented 3 days ago • edited
**"Option 2 for team building mode is not yet available."**
